name: JS+CSS Coding Standards

on:
  push:
    branches: [ trunk, develop ]
  pull_request:
    branches: [ trunk, develop ]

permissions:
  contents: read

jobs:
  lint-js_css-files:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup proper Node.js version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run JS linter
        run: npm run lint:scripts

      - name: Run CSS linter
        run: npm run lint:styles
